name: app_device_integrity
description: "This plugin simplifies app attestation by using Apple's App Attest and Google's Play Integrity to generate tokens for your Server to decrypt and verify reliable device access."
version: 1.0.5
homepage: https://bubotech.club

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: co.bubotech.app_device_integrity
        pluginClass: AppDeviceIntegrityPlugin
      ios:
        pluginClass: AppDeviceIntegrityPlugin