[package]
name = "rust_api_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
awc = "3.0"  # Actix Web Client
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
