[package]
name = "rust_api_server"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "1.0.5" }
actix-web = "4.0"
awc = "3.0"  # Actix Web Client
serde_json = "1.0"
app_attest_core = { path = "../core/" }
methods = { path = "../methods" }